# Generated by Django 5.2.16 on 2026-07-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goodimage_image_url_goodimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/%Y/%m/'),
        ),
    ]
